//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyCalls.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class DailyCall
    {
        public int ID { get; set; }

        [Display(Name = "Client Name")]
        public string Name { get; set; }

        [Display(Name = "Client Reference")]
        public string ClientReference { get; set; }

        [Display(Name = "Telephone Number")]
        public string TelephoneNumber { get; set; }

        public Nullable<System.DateTime> Date { get; set; }

        [Display(Name = "Outcome Of Call")]
        public Nullable<int> OutcomeId { get; set; }

        [Display(Name = "Last Called")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> LastCalled { get; set; }

        public IEnumerable<SelectListItem> Outcomes { get; set; }

       
        public virtual CallOutcomeList CallOutcomeList { get; set; }
    }
}
