//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyCalls.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Phone_SystemEntities10 : DbContext
    {
        public Phone_SystemEntities10()
            : base("name=Phone_SystemEntities10")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CallOutcomeList> CallOutcomeLists { get; set; }
        public virtual DbSet<DailyCall> DailyCalls { get; set; }
    
        public virtual int pr_InsertCallDetails(string name, string clientReference, string telephoneNumber, Nullable<System.DateTime> date, Nullable<int> outcomeId, Nullable<System.DateTime> lastCalled)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var clientReferenceParameter = clientReference != null ?
                new ObjectParameter("ClientReference", clientReference) :
                new ObjectParameter("ClientReference", typeof(string));
    
            var telephoneNumberParameter = telephoneNumber != null ?
                new ObjectParameter("TelephoneNumber", telephoneNumber) :
                new ObjectParameter("TelephoneNumber", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var outcomeIdParameter = outcomeId.HasValue ?
                new ObjectParameter("OutcomeId", outcomeId) :
                new ObjectParameter("OutcomeId", typeof(int));
    
            var lastCalledParameter = lastCalled.HasValue ?
                new ObjectParameter("LastCalled", lastCalled) :
                new ObjectParameter("LastCalled", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_InsertCallDetails", nameParameter, clientReferenceParameter, telephoneNumberParameter, dateParameter, outcomeIdParameter, lastCalledParameter);
        }
    }
}
